### ISSUE TITLE
usage in release pipelines

### ISSUE THREAD

**Issue by cforce** [microsoft/azure-pipelines-artifact-caching-tasks#26] opened 2019-10-17 09:04 UTC
How can i make use of (maven) caching in a release pipeline (non yaml)

**Comment by erdennis13** [comment] 2019-10-17 19:53
This will involve redirecting the maven repo to the repository's directory. E.g. `-Dmaven.repo.local=$(Build.Repository.LocalPath)/cache/.m2`.

Marking as duplicate of #23

**Closed by erdennis13** 2019-10-17 19:53 UTC
